# Generated by Django 4.1.3 on 2026-06-29 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g., AG01', max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.CharField(help_text='Acronym (e.g., ADI, MLSTP)', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PollingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_number', models.PositiveIntegerField()),
                ('name', models.CharField(help_text='e.g., Escola Pantufo - Mesa 1', max_length=100)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polling_stations', to='poll.constituency')),
            ],
            options={
                'unique_together': {('constituency', 'station_number')},
            },
        ),
        migrations.CreateModel(
            name='PollingStationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_type', models.CharField(choices=[('Legislative', 'Legislative'), ('Presidential', 'Presidential'), ('Autarchic', 'Autarchic')], max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('abstentions', models.PositiveIntegerField(default=0)),
                ('blank_votes', models.PositiveIntegerField(default=0)),
                ('null_votes', models.PositiveIntegerField(default=0)),
                ('polling_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.pollingstation')),
            ],
            options={
                'unique_together': {('polling_station', 'election_type', 'year')},
            },
        ),
        migrations.CreateModel(
            name='ElectoralCircle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circles', to='poll.district')),
            ],
        ),
        migrations.AddField(
            model_name='constituency',
            name='circle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constituencies', to='poll.electoralcircle'),
        ),
        migrations.CreateModel(
            name='CandidateRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_type', models.CharField(choices=[('Legislative', 'Legislative'), ('Presidential', 'Presidential'), ('Autarchic', 'Autarchic')], max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('representative_name', models.CharField(help_text='Main runner name', max_length=150)),
                ('contender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.contender')),
            ],
            options={
                'unique_together': {('contender', 'election_type', 'year')},
            },
        ),
        migrations.CreateModel(
            name='VoteCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_votes', models.PositiveIntegerField(default=0)),
                ('candidate_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.candidateregistration')),
                ('polling_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='poll.pollingstationresult')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('polling_result', 'candidate_registration')},
            },
        ),
        migrations.CreateModel(
            name='AccumulatedResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('Constituency', 'Constituency Total'), ('Circle', 'Circle Total'), ('District', 'District Total'), ('National', 'National Total')], max_length=20)),
                ('election_type', models.CharField(choices=[('Legislative', 'Legislative'), ('Presidential', 'Presidential'), ('Autarchic', 'Autarchic')], max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('total_votes', models.PositiveIntegerField(default=0)),
                ('estimated_seats', models.PositiveIntegerField(default=0, help_text='Deputados / Vereadores calculated via Hondt method.')),
                ('candidate_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.candidateregistration')),
                ('circle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.electoralcircle')),
                ('constituency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.constituency')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.district')),
            ],
            options={
                'unique_together': {('scope', 'district', 'circle', 'constituency', 'candidate_registration', 'election_type', 'year')},
            },
        ),
    ]
