# Generated by Django 4.1.3 on 2026-06-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_constituency_contender_district_pollingstation_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accumulatedresult',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='accumulatedresult',
            constraint=models.UniqueConstraint(condition=models.Q(('circle__isnull', True), ('constituency__isnull', True), ('district__isnull', True)), fields=('scope', 'candidate_registration', 'election_type', 'year'), name='unique_accumulated_national'),
        ),
        migrations.AddConstraint(
            model_name='accumulatedresult',
            constraint=models.UniqueConstraint(condition=models.Q(('circle__isnull', True), ('constituency__isnull', True), ('district__isnull', False)), fields=('scope', 'district', 'candidate_registration', 'election_type', 'year'), name='unique_accumulated_district'),
        ),
        migrations.AddConstraint(
            model_name='accumulatedresult',
            constraint=models.UniqueConstraint(condition=models.Q(('circle__isnull', False), ('constituency__isnull', True), ('district__isnull', False)), fields=('scope', 'district', 'circle', 'candidate_registration', 'election_type', 'year'), name='unique_accumulated_circle'),
        ),
        migrations.AddConstraint(
            model_name='accumulatedresult',
            constraint=models.UniqueConstraint(condition=models.Q(('circle__isnull', False), ('constituency__isnull', False), ('district__isnull', False)), fields=('scope', 'district', 'circle', 'constituency', 'candidate_registration', 'election_type', 'year'), name='unique_accumulated_constituency'),
        ),
    ]
