# Generated by Django 4.1.3 on 2026-06-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_alter_accumulatedresult_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='accumulatedresult',
            name='unique_accumulated_national',
        ),
        migrations.RemoveConstraint(
            model_name='accumulatedresult',
            name='unique_accumulated_district',
        ),
        migrations.RemoveConstraint(
            model_name='accumulatedresult',
            name='unique_accumulated_circle',
        ),
        migrations.RemoveConstraint(
            model_name='accumulatedresult',
            name='unique_accumulated_constituency',
        ),
        migrations.AddConstraint(
            model_name='accumulatedresult',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'National')), fields=('scope', 'candidate_registration', 'election_type', 'year'), name='unique_accumulated_national'),
        ),
        migrations.AddConstraint(
            model_name='accumulatedresult',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'District')), fields=('scope', 'district', 'candidate_registration', 'election_type', 'year'), name='unique_accumulated_district'),
        ),
        migrations.AddConstraint(
            model_name='accumulatedresult',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'Circle')), fields=('scope', 'circle', 'candidate_registration', 'election_type', 'year'), name='unique_accumulated_circle'),
        ),
        migrations.AddConstraint(
            model_name='accumulatedresult',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'Constituency')), fields=('scope', 'constituency', 'candidate_registration', 'election_type', 'year'), name='unique_accumulated_constituency'),
        ),
    ]
