# Generated by Django 4.1.3 on 2026-06-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_remove_accumulatedresult_unique_accumulated_national_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('electoral_staff', 'Electoral Staff'), ('admin', 'Administrator')], default='citizen', max_length=20),
        ),
    ]
