# Generated by Django 4.1.3 on 2026-06-29 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollingstationresult',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pollingstationresult',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pollingstationresult',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pollingstationresult',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_results', to=settings.AUTH_USER_MODEL),
        ),
    ]
