# Generated by Django 4.1.3 on 2026-06-30 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_add_unique_constraint_to_accumulatedresult'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accumulatedresult',
            unique_together=set(),
        ),
    ]
