# Generated by Django 4.1.3 on 2026-06-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_alter_accumulatedresult_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='accumulatedresult',
            name='total_abstentions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accumulatedresult',
            name='total_blank_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accumulatedresult',
            name='total_null_votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
