# Generated by Django 4.1.3 on 2026-06-30 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0009_accumulatedresult_total_abstentions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accumulatedresult',
            name='total_abstentions',
        ),
        migrations.RemoveField(
            model_name='accumulatedresult',
            name='total_blank_votes',
        ),
        migrations.RemoveField(
            model_name='accumulatedresult',
            name='total_null_votes',
        ),
    ]
